// AUTO-GENERATED by scripts/check-brand-contrast.mjs. Do not edit by hand — run `npm run check:contrast`.
// Generated on: 2026-05-23
// Audit scope: brand foregrounds on production text-bearing surfaces (white, offwhite, navy, ink).
// Source-of-truth for token hexes: src/index.css (CSS custom properties).
// Waivers documented in: vault/Planning/Architecture-Key.md → WCAG Contrast Exceptions.

export interface BrandContrastWaiver {
  id: string
  reason: string
}

export interface BrandContrastEntry {
  fg: string
  bg: string
  fgHex: string
  bgHex: string
  ratio: number
  aaNormal: boolean
  aaLarge: boolean
  waiver: BrandContrastWaiver | null
}

export const BRAND_CONTRAST_MANIFEST: BrandContrastEntry[] = [
  { fg: "accent", bg: "ink", fgHex: "#3D6FE0", bgHex: "#0A0B2E", ratio: 4.13, aaNormal: false, aaLarge: true, waiver: { id: "R-A3", reason: "Sober accent #3D6FE0 on ink ≈ 4.10:1 — passes AA Large only; same R-A3 reservation as accent-on-navy." } },
  { fg: "accent", bg: "navy", fgHex: "#3D6FE0", bgHex: "#0D0D3A", ratio: 4.00, aaNormal: false, aaLarge: true, waiver: { id: "R-A3", reason: "Sober accent #3D6FE0 on navy ≈ 3.97:1 — passes AA Large, reserved for large/decorative usage on dark surfaces (Epic 6)." } },
  { fg: "accent", bg: "offwhite", fgHex: "#3D6FE0", bgHex: "#F4F6FA", ratio: 4.27, aaNormal: false, aaLarge: true, waiver: { id: "R-A3", reason: "Sober accent #3D6FE0 on offwhite — same R-A3 reservation as accent-on-white." } },
  { fg: "accent", bg: "white", fgHex: "#3D6FE0", bgHex: "#FFFFFF", ratio: 4.62, aaNormal: true, aaLarge: true, waiver: { id: "R-A3", reason: "Sober accent #3D6FE0 on white ≈ 4.65:1 — borderline AA Normal; treat as R-A3 accent usage (large/decorative preferred) until Epic 6 light-surface contrast pass." } },
  { fg: "deep", bg: "ink", fgHex: "#0055F0", bgHex: "#0A0B2E", ratio: 3.23, aaNormal: false, aaLarge: true, waiver: { id: "R-NT1", reason: "Brand-deep is a light-surface accent; never paired on ink in production." } },
  { fg: "deep", bg: "navy", fgHex: "#0055F0", bgHex: "#0D0D3A", ratio: 3.13, aaNormal: false, aaLarge: true, waiver: { id: "R-NT1", reason: "Brand-deep is a light-surface accent; not paired on dark navy surfaces in production." } },
  { fg: "deep", bg: "offwhite", fgHex: "#0055F0", bgHex: "#F4F6FA", ratio: 5.46, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "deep", bg: "white", fgHex: "#0055F0", bgHex: "#FFFFFF", ratio: 5.90, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "electric-blue", bg: "ink", fgHex: "#0075F0", bgHex: "#0A0B2E", ratio: 4.37, aaNormal: false, aaLarge: true, waiver: { id: "R-A2", reason: "Electric Blue on ink remains in the R-A2 decorative family; reserved for large text on dark surfaces." } },
  { fg: "electric-blue", bg: "navy", fgHex: "#0075F0", bgHex: "#0D0D3A", ratio: 4.23, aaNormal: false, aaLarge: true, waiver: { id: "R-A2", reason: "Electric Blue on navy is a decorative accent (gradient stops, hairlines); reserve for large text only on dark surfaces." } },
  { fg: "electric-blue", bg: "offwhite", fgHex: "#0075F0", bgHex: "#F4F6FA", ratio: 4.04, aaNormal: false, aaLarge: true, waiver: { id: "R-A2", reason: "Electric Blue reserved for large text only, gradient stops, decorative accents." } },
  { fg: "electric-blue", bg: "white", fgHex: "#0075F0", bgHex: "#FFFFFF", ratio: 4.37, aaNormal: false, aaLarge: true, waiver: { id: "R-A2", reason: "Electric Blue reserved for large text only, gradient stops, decorative accents." } },
  { fg: "highlight", bg: "ink", fgHex: "#00A0F0", bgHex: "#0A0B2E", ratio: 6.62, aaNormal: true, aaLarge: true, waiver: { id: "R-NT1", reason: "Legacy gradient stop never paired with ink in production (ink is Epic 6-only)." } },
  { fg: "highlight", bg: "navy", fgHex: "#00A0F0", bgHex: "#0D0D3A", ratio: 6.42, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "highlight", bg: "offwhite", fgHex: "#00A0F0", bgHex: "#F4F6FA", ratio: 2.66, aaNormal: false, aaLarge: false, waiver: { id: "R-A2", reason: "Highlight #00A0F0 is the same decorative blue family as electric-blue — reserve for large text, gradient stops, decorative accents." } },
  { fg: "highlight", bg: "white", fgHex: "#00A0F0", bgHex: "#FFFFFF", ratio: 2.88, aaNormal: false, aaLarge: false, waiver: { id: "R-A2", reason: "Highlight #00A0F0 is the same decorative blue family as electric-blue — reserve for large text, gradient stops, decorative accents." } },
  { fg: "ink", bg: "navy", fgHex: "#0A0B2E", bgHex: "#0D0D3A", ratio: 1.03, aaNormal: false, aaLarge: false, waiver: { id: "R-NT1", reason: "Surface-on-surface pair; ink and navy are both dark surfaces — never text in production." } },
  { fg: "ink", bg: "offwhite", fgHex: "#0A0B2E", bgHex: "#F4F6FA", ratio: 17.64, aaNormal: true, aaLarge: true, waiver: { id: "R-NT1", reason: "Ink is a dark surface token; never used as foreground on light surfaces in production." } },
  { fg: "ink", bg: "white", fgHex: "#0A0B2E", bgHex: "#FFFFFF", ratio: 19.09, aaNormal: true, aaLarge: true, waiver: { id: "R-NT1", reason: "Ink is a dark surface token; never used as foreground on light surfaces in production." } },
  { fg: "muted", bg: "ink", fgHex: "#8080A0", bgHex: "#0A0B2E", ratio: 5.01, aaNormal: true, aaLarge: true, waiver: { id: "R-NT1", reason: "Legacy muted not paired with ink — Epic 6 dark surfaces use muted-token / offwhite." } },
  { fg: "muted", bg: "navy", fgHex: "#8080A0", bgHex: "#0D0D3A", ratio: 4.85, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "muted", bg: "offwhite", fgHex: "#8080A0", bgHex: "#F4F6FA", ratio: 3.52, aaNormal: false, aaLarge: true, waiver: { id: "R-M1", reason: "Muted #8080A0 reserved for de-emphasized helper text and meta labels — passes AA Large only." } },
  { fg: "muted", bg: "white", fgHex: "#8080A0", bgHex: "#FFFFFF", ratio: 3.81, aaNormal: false, aaLarge: true, waiver: { id: "R-M1", reason: "Muted #8080A0 reserved for de-emphasized helper text and meta labels — passes AA Large only." } },
  { fg: "navy", bg: "ink", fgHex: "#0D0D3A", bgHex: "#0A0B2E", ratio: 1.03, aaNormal: false, aaLarge: false, waiver: { id: "R-NT1", reason: "Surface-on-surface pair; ink and navy are both dark surfaces — never text in production." } },
  { fg: "navy", bg: "offwhite", fgHex: "#0D0D3A", bgHex: "#F4F6FA", ratio: 17.09, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "navy", bg: "white", fgHex: "#0D0D3A", bgHex: "#FFFFFF", ratio: 18.49, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "offwhite", bg: "ink", fgHex: "#F4F6FA", bgHex: "#0A0B2E", ratio: 17.64, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "offwhite", bg: "navy", fgHex: "#F4F6FA", bgHex: "#0D0D3A", ratio: 17.09, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "offwhite", bg: "white", fgHex: "#F4F6FA", bgHex: "#FFFFFF", ratio: 1.08, aaNormal: false, aaLarge: false, waiver: { id: "R-NT1", reason: "Surface-on-surface pair; never used for text in production." } },
  { fg: "slate", bg: "ink", fgHex: "#404070", bgHex: "#0A0B2E", ratio: 1.99, aaNormal: false, aaLarge: false, waiver: { id: "R-NT1", reason: "Slate is a light-surface label; ink dark surface uses offwhite or white." } },
  { fg: "slate", bg: "navy", fgHex: "#404070", bgHex: "#0D0D3A", ratio: 1.92, aaNormal: false, aaLarge: false, waiver: { id: "R-NT1", reason: "Slate is a mid-tone label for light surfaces only; dark surfaces use offwhite or white." } },
  { fg: "slate", bg: "offwhite", fgHex: "#404070", bgHex: "#F4F6FA", ratio: 8.88, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "slate", bg: "white", fgHex: "#404070", bgHex: "#FFFFFF", ratio: 9.61, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "white", bg: "ink", fgHex: "#FFFFFF", bgHex: "#0A0B2E", ratio: 19.09, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "white", bg: "navy", fgHex: "#FFFFFF", bgHex: "#0D0D3A", ratio: 18.49, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "white", bg: "offwhite", fgHex: "#FFFFFF", bgHex: "#F4F6FA", ratio: 1.08, aaNormal: false, aaLarge: false, waiver: { id: "R-NT1", reason: "Surface-on-surface pair; never used for text in production." } },
]

export const EPIC7_DARK_CONTRAST_MANIFEST: BrandContrastEntry[] = [
  { fg: "foreground", bg: "background", fgHex: "#FAFAFA", bgHex: "#0A0A0A", ratio: 18.97, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "card-foreground", bg: "card", fgHex: "#FAFAFA", bgHex: "#0A0A0A", ratio: 18.97, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "popover-foreground", bg: "popover", fgHex: "#FAFAFA", bgHex: "#0A0A0A", ratio: 18.97, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "primary-foreground", bg: "primary", fgHex: "#171717", bgHex: "#FAFAFA", ratio: 17.18, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "secondary-foreground", bg: "secondary", fgHex: "#FAFAFA", bgHex: "#262626", ratio: 14.50, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "muted-foreground", bg: "muted", fgHex: "#A1A1A1", bgHex: "#262626", ratio: 5.86, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "accent-foreground", bg: "accent", fgHex: "#FAFAFA", bgHex: "#262626", ratio: 14.50, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "destructive-foreground", bg: "destructive", fgHex: "#FAFAFA", bgHex: "#82181A", ratio: 9.60, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "sidebar-foreground", bg: "sidebar", fgHex: "#FAFAFA", bgHex: "#171717", ratio: 17.18, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "sidebar-primary-foreground", bg: "sidebar-primary", fgHex: "#FAFAFA", bgHex: "#1447E6", ratio: 6.55, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "sidebar-accent-foreground", bg: "sidebar-accent", fgHex: "#FAFAFA", bgHex: "#262626", ratio: 14.50, aaNormal: true, aaLarge: true, waiver: null },
]
