// AUTO-GENERATED by scripts/check-brand-contrast.mjs. Do not edit by hand — run `npm run check:contrast`.
// Generated on: 2026-05-16
// Audit scope: brand foregrounds on production text-bearing surfaces (white, offwhite, navy).
// Source-of-truth for token hexes: src/index.css (CSS custom properties).
// Waivers documented in: vault/Planning/Architecture-Key.md → WCAG Contrast Exceptions.

export interface BrandContrastWaiver {
  id: string
  reason: string
}

export interface BrandContrastEntry {
  fg: string
  bg: string
  fgHex: string
  bgHex: string
  ratio: number
  aaNormal: boolean
  aaLarge: boolean
  waiver: BrandContrastWaiver | null
}

export const BRAND_CONTRAST_MANIFEST: BrandContrastEntry[] = [
  { fg: "deep", bg: "navy", fgHex: "#0055F0", bgHex: "#0D0D3A", ratio: 3.13, aaNormal: false, aaLarge: true, waiver: { id: "R-NT1", reason: "Brand-deep is a light-surface accent; not paired on dark navy surfaces in production." } },
  { fg: "deep", bg: "offwhite", fgHex: "#0055F0", bgHex: "#F4F6FA", ratio: 5.46, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "deep", bg: "white", fgHex: "#0055F0", bgHex: "#FFFFFF", ratio: 5.90, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "electric-blue", bg: "navy", fgHex: "#0075F0", bgHex: "#0D0D3A", ratio: 4.23, aaNormal: false, aaLarge: true, waiver: { id: "R-A2", reason: "Electric Blue on navy is a decorative accent (gradient stops, hairlines); reserve for large text only on dark surfaces." } },
  { fg: "electric-blue", bg: "offwhite", fgHex: "#0075F0", bgHex: "#F4F6FA", ratio: 4.04, aaNormal: false, aaLarge: true, waiver: { id: "R-A2", reason: "Electric Blue reserved for large text only, gradient stops, decorative accents." } },
  { fg: "electric-blue", bg: "white", fgHex: "#0075F0", bgHex: "#FFFFFF", ratio: 4.37, aaNormal: false, aaLarge: true, waiver: { id: "R-A2", reason: "Electric Blue reserved for large text only, gradient stops, decorative accents." } },
  { fg: "highlight", bg: "navy", fgHex: "#00A0F0", bgHex: "#0D0D3A", ratio: 6.42, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "highlight", bg: "offwhite", fgHex: "#00A0F0", bgHex: "#F4F6FA", ratio: 2.66, aaNormal: false, aaLarge: false, waiver: { id: "R-A2", reason: "Highlight #00A0F0 is the same decorative blue family as electric-blue — reserve for large text, gradient stops, decorative accents." } },
  { fg: "highlight", bg: "white", fgHex: "#00A0F0", bgHex: "#FFFFFF", ratio: 2.88, aaNormal: false, aaLarge: false, waiver: { id: "R-A2", reason: "Highlight #00A0F0 is the same decorative blue family as electric-blue — reserve for large text, gradient stops, decorative accents." } },
  { fg: "muted", bg: "navy", fgHex: "#8080A0", bgHex: "#0D0D3A", ratio: 4.85, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "muted", bg: "offwhite", fgHex: "#8080A0", bgHex: "#F4F6FA", ratio: 3.52, aaNormal: false, aaLarge: true, waiver: { id: "R-M1", reason: "Muted #8080A0 reserved for de-emphasized helper text and meta labels — passes AA Large only." } },
  { fg: "muted", bg: "white", fgHex: "#8080A0", bgHex: "#FFFFFF", ratio: 3.81, aaNormal: false, aaLarge: true, waiver: { id: "R-M1", reason: "Muted #8080A0 reserved for de-emphasized helper text and meta labels — passes AA Large only." } },
  { fg: "navy", bg: "offwhite", fgHex: "#0D0D3A", bgHex: "#F4F6FA", ratio: 17.09, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "navy", bg: "white", fgHex: "#0D0D3A", bgHex: "#FFFFFF", ratio: 18.49, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "offwhite", bg: "navy", fgHex: "#F4F6FA", bgHex: "#0D0D3A", ratio: 17.09, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "offwhite", bg: "white", fgHex: "#F4F6FA", bgHex: "#FFFFFF", ratio: 1.08, aaNormal: false, aaLarge: false, waiver: { id: "R-NT1", reason: "Surface-on-surface pair; never used for text in production." } },
  { fg: "slate", bg: "navy", fgHex: "#404070", bgHex: "#0D0D3A", ratio: 1.92, aaNormal: false, aaLarge: false, waiver: { id: "R-NT1", reason: "Slate is a mid-tone label for light surfaces only; dark surfaces use offwhite or white." } },
  { fg: "slate", bg: "offwhite", fgHex: "#404070", bgHex: "#F4F6FA", ratio: 8.88, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "slate", bg: "white", fgHex: "#404070", bgHex: "#FFFFFF", ratio: 9.61, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "white", bg: "navy", fgHex: "#FFFFFF", bgHex: "#0D0D3A", ratio: 18.49, aaNormal: true, aaLarge: true, waiver: null },
  { fg: "white", bg: "offwhite", fgHex: "#FFFFFF", bgHex: "#F4F6FA", ratio: 1.08, aaNormal: false, aaLarge: false, waiver: { id: "R-NT1", reason: "Surface-on-surface pair; never used for text in production." } },
]
